# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[time]
disabled = false
format = '[$time ]($style)'
time_format = '%H:%M'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
format = 'via [(\($virtualenv\) )]($style)'

[bun]
disabled = true

[nodejs]
disabled = true

[aws]
format = 'on [$symbol($profile )(\[$duration\] )]($style)'

[kubernetes]
disabled = false
