#!/usr/bin/env bash

set -x

# ====== Variables =============================

declare -A gaps
declare -A color

gaps["top"]="8"
gaps["bottom"]="8"
gaps["left"]="8"
gaps["right"]="8"
gaps["inner"]="8"

color["active"]="0x00000000"
color["normal"]="0x00000000"
color["preselect"]="0x00000000"

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# ===== Tiling setting =========================

yabai -m config layout                      bsp

yabai -m config external_bar                all:36:0
yabai -m config top_padding                 "${gaps["top"]}"
yabai -m config bottom_padding              "${gaps["bottom"]}"
yabai -m config left_padding                "${gaps["left"]}"
yabai -m config right_padding               "${gaps["right"]}"
yabai -m config window_gap                  "${gaps["inner"]}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config window_shadow               float
yabai -m window_placement                   second_child

yabai -m window_animation_duration          1
yabai -m window_opacity_duration            1

yabai -m config window_border               on
yabai -m config window_border_radius        8
yabai -m config window_border_width         2
yabai -m config window_border_blur          on
yabai -m config window_border_hidpi         on
yabai -m config active_window_border_color  0x01000000
yabai -m config normal_window_border_color  0x01000000
yabai -m config insert_feedback_color       0x01000000

yabai -m config window_opacity              on
yabai -m config active_window_opacity       0.98
yabai -m config normal_window_opacity       0.90
yabai -m config split_ratio                 0.50

yabai -m config auto_balance                off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

# ===== Rules ==================================

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="1Password 7" app="^1Password 7$" manage=off
yabai -m rule --add label="Docker Desktop" app="^Docker Desktop$" manage=off
yabai -m rule --add label="Sonos" app="^Sonos$" manage=off

# ===== Borders ================================
border_options=(
	style=round
	width=5.0
	hidpi=on
	active_color=0xffe1e3e4
	inactive_color=0xff494d64
)
borders "${options[@]}"

# ==============================================

set +x
printf "yabai: configuration loaded...\\n"
